import fs from "node:fs";
import path from "node:path";
import os from "node:os";

const SKELETON_DIR = path.join(os.homedir(), ".skeleton");
const SKELETON_ENV = path.join(SKELETON_DIR, ".env");

/**
 * Load environment variables from .env files (Hermes-style).
 *
 * Load order (first wins, later files don't overwrite):
 *   1. ~/.skeleton/.env  — user secrets (API keys, tokens)
 *   2. CWD/.env          — project-level overrides
 *
 * This keeps secrets out of config.yaml while still making them
 * available for ${VAR} substitution and provider apiKeyEnvVars.
 */
export function loadEnv(envPath?: string): void {
  const searchPaths = [
    SKELETON_ENV,          // ~/.skeleton/.env — secrets
    envPath ?? path.join(process.cwd(), ".env"),  // project .env
  ];

  for (const p of searchPaths) {
    if (!fs.existsSync(p)) continue;
    for (const line of fs.readFileSync(p, "utf-8").split("\n")) {
      const trimmed = line.trim();
      if (!trimmed || trimmed.startsWith("#")) continue;
      const eq = trimmed.indexOf("=");
      if (eq === -1) continue;
      const key = trimmed.slice(0, eq).trim();
      const val = trimmed.slice(eq + 1).trim();
      // Remove surrounding quotes if present
      const unquoted = val.startsWith('"') && val.endsWith('"')
        ? val.slice(1, -1)
        : val.startsWith("'") && val.endsWith("'")
          ? val.slice(1, -1)
          : val;
      if (!process.env[key]) process.env[key] = unquoted;
    }
  }
}

/** Return the path to ~/.skeleton/.env (for setup wizard) */
export function getSkeletonEnvPath(): string {
  return SKELETON_ENV;
}

/** Write a key=value line to ~/.skeleton/.env (creates file if needed) */
export function writeSkeletonEnv(entries: Record<string, string>): void {
  if (!fs.existsSync(SKELETON_DIR)) {
    fs.mkdirSync(SKELETON_DIR, { recursive: true });
  }

  // Read existing entries to preserve manual additions
  const existing: Record<string, string> = {};
  if (fs.existsSync(SKELETON_ENV)) {
    for (const line of fs.readFileSync(SKELETON_ENV, "utf-8").split("\n")) {
      const trimmed = line.trim();
      if (!trimmed || trimmed.startsWith("#")) continue;
      const eq = trimmed.indexOf("=");
      if (eq === -1) continue;
      const key = trimmed.slice(0, eq).trim();
      const val = trimmed.slice(eq + 1).trim();
      existing[key] = val;
    }
  }

  // Merge new entries (overwrite existing with same key)
  Object.assign(existing, entries);

  // Write back with comments
  const lines = [
    "# Skeleton secrets — auto-generated by `skeleton setup`",
    "# API keys are stored here so they don't leak into config.yaml",
    "",
  ];
  for (const [key, val] of Object.entries(existing).sort(([a], [b]) => a.localeCompare(b))) {
    lines.push(`${key}=${val}`);
  }

  fs.writeFileSync(SKELETON_ENV, lines.join("\n") + "\n", "utf-8");
}
