import fs from "node:fs";
import path from "node:path";
import os from "node:os";
import chalk from "chalk";
import readline from "node:readline";
import { MCP_CATEGORIES } from "@skeleton/core";

const SKELETON_DIR = path.join(os.homedir(), ".skeleton");
const CONFIG_FILE = path.join(SKELETON_DIR, "skeleton.yaml");

function question(rl: readline.Interface, prompt: string): Promise<string> {
  return new Promise((resolve) => {
    rl.question(prompt, (answer) => resolve(answer.trim()));
  });
}

function questionChoice(rl: readline.Interface, prompt: string, choices: string[], defaultIdx: number = 0): Promise<string> {
  const display = choices.map((c, i) => i === defaultIdx ? chalk.cyan(`[${i + 1}]`) + ` ${c}` : `(${i + 1}) ${c}`).join("  ");
  return question(rl, `${prompt} ${display} `).then((ans) => {
    const idx = parseInt(ans) - 1;
    if (idx >= 0 && idx < choices.length) return choices[idx];
    return choices[defaultIdx];
  });
}

export async function runSetup(): Promise<void> {
  console.log(chalk.cyan("\n  Skeleton Setup Wizard\n"));

  if (!fs.existsSync(SKELETON_DIR)) {
    fs.mkdirSync(SKELETON_DIR, { recursive: true });
  }

  const rl = readline.createInterface({ input: process.stdin, output: process.stdout });

  // 1. Protocol
  const protocol = await questionChoice(rl, "LLM Protocol:", ["openai", "anthropic"], 0);

  // 2. API Key
  let apiKey = process.env.SKELETON_API_KEY ?? "";
  if (!apiKey) {
    apiKey = await question(rl, "API Key: ");
  } else {
    console.log(chalk.gray(`  API Key: ${apiKey.slice(0, 8)}... (from env)`));
  }

  // 3. Base URL
  const defaultBase = protocol === "openai" ? "https://api.openai.com" : "https://api.anthropic.com";
  const baseUrl = await question(rl, `Base URL [${defaultBase}]: `) || defaultBase;

  // 4. Model
  const defaultModel = protocol === "openai" ? "gpt-4o" : "claude-sonnet-4-20250514";
  const model = await question(rl, `Model [${defaultModel}]: `) || defaultModel;

  // 5. MCP servers
  console.log(chalk.cyan("\n  MCP Servers (enable/disable):\n"));
  const mcpChoices: Record<string, string[]> = {};

  for (const [cat, label] of Object.entries(MCP_CATEGORIES)) {
    const enable = await questionChoice(rl, `  ${label}:`, ["skip", "enable all", "pick individually"], 0);
    if (enable === "enable all") {
      mcpChoices[cat] = ["*"];
    } else if (enable === "pick individually") {
      console.log(chalk.gray(`    (Set SKELETON_MCP_<NAME>=true for individual servers in this category)`));
    }
  }

  // Build YAML
  const yamlLines = [
    `# Skeleton configuration — generated by skeleton setup`,
    ``,
    `llm:`,
    `  protocol: ${protocol}`,
    `  apiKey: \${SKELETON_API_KEY}`,
    `  baseUrl: ${baseUrl}`,
    `  model: ${model}`,
    ``,
  ];

  const hasMcp = Object.keys(mcpChoices).length > 0;
  if (hasMcp) {
    yamlLines.push(`mcp:`);
    yamlLines.push(`  servers:`);
    for (const [cat, names] of Object.entries(mcpChoices)) {
      if (names.includes("*")) {
        yamlLines.push(`    # ${MCP_CATEGORIES[cat] as string}: all servers (enable individually via env)`);
      }
    }
    yamlLines.push(``);
  }

  const yamlContent = yamlLines.join("\n");

  console.log(chalk.cyan("\n  Generated configuration:\n"));
  console.log(chalk.gray(yamlContent));

  const write = await questionChoice(rl, "Write to ~/.skeleton/skeleton.yaml?", ["yes", "no"], 0);
  if (write === "yes") {
    fs.writeFileSync(CONFIG_FILE, yamlContent, "utf-8");
    console.log(chalk.green(`\n  ✓ Configuration saved to ${CONFIG_FILE}`));
  } else {
    console.log(chalk.gray("\n  Skipped. You can create skeleton.yaml manually."));
  }

  // 6. Environment hint
  console.log(chalk.cyan("\n  Environment variables:"));
  console.log(chalk.gray(`  SKELETON_API_KEY=${apiKey ? "***" : "<your-key>"}`));
  console.log(chalk.gray(`  SKELETON_PROTOCOL=${protocol}`));
  console.log(chalk.gray(`  SKELETON_MODEL=${model}`));
  console.log(chalk.gray(`  SKELETON_BASE_URL=${baseUrl}`));
  console.log();

  rl.close();
}
